# Taken from: https://github.com/RedHatInsights/insights-ingress-go/blob/master/development/local-dev-start.yml

# This podman compose file stands up local dependencies for
# Kafka, Zookeeper, and Minio and optionally insights-ingress-go itself.
# Please consult README.md for bucket creation steps
version: "3"
services:
  zookeeper:
    image: docker.io/confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_SERVER_ID=1
    networks:
      - worker

  kafka:
    image: docker.io/confluentinc/cp-kafka
    ports:
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - worker

  minio:
    image: docker.io/minio/minio
    command: server --address 0.0.0.0:9000 --console-address 0.0.0.0:9990 /data
    volumes:
      - "./minio-conf:/mnt/config:z"
      - "./minio-data/.minio:/mnt/data:z"
    ports:
      - 9000:9000
      - 9990:9990
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    networks:
      - worker

  minio-createbucket:
    image: docker.io/minio/mc
    depends_on:
      - minio
    restart: on-failure
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} || exit 1;
      /usr/bin/mc mb --ignore-existing myminio/insights-upload-perma;
      /usr/bin/mc policy set public myminio/insights-upload-perma;
      "
    networks:
      - worker

  ingress:
    image: quay.io/redhat-services-prod/hcc-pipeline-tenant/insights-ingress-go:latest
    ports:
      - 3000:3000
    mem_limit: 512M
    environment:
      - INGRESS_STAGEBUCKET=insights-upload-perma
        # INGRESS_VALID_UPLOAD_TYPES is required. This is derived from content type. ex: vnd.redhat.advisor.thing+tgz
      - INGRESS_VALID_UPLOAD_TYPES=$INGRESS_VALID_UPLOAD_TYPES
      - OPENSHIFT_BUILD_COMMIT=somestring
      - INGRESS_METRICSPORT=8081
      - INGRESS_MAXSIZE=104857600
      - INGRESS_MINIODEV=true
      - INGRESS_MINIOACCESSKEY=$MINIO_ACCESS_KEY
      - INGRESS_MINIOSECRETKEY=$MINIO_SECRET_KEY
      - INGRESS_MINIOENDPOINT=minio:9000
      - INGRESS_AUTH=false
    depends_on:
      - kafka
      - minio
    networks:
      - worker

  nginx:
    image: docker.io/nginx:latest
    volumes:
      - ./nginx/data:/www/data/data:z
      - ./nginx/worker.conf:/etc/nginx/conf.d/default.conf:z
    ports:
      - "8000:80"
    depends_on:
      - ingress
    networks:
      - worker

  mqtt:
    image: docker.io/eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes: "./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:Z"
    networks:
      - worker

networks:
  worker: {}
